### ISSUE TITLE
Arabic text is not valid

### ISSUE THREAD

**Issue by Hamed1Hamed** [DataScienceUIBK/ArabicaQA#1]
Thanks for the good work. However, the datasets in CSV format do not have an Arabic text. I think you should save it with encoding='utf-8-sig'.
Looking forward to seeing your update. 
![ArabicaQA A Comprehensive Dataset for Arabic Question](https://github.com/DataScienceUIBK/ArabicaQA/assets/18492341/6291fb3a-6b6d-4e93-b840-592cd0b145fb)

**Comment by abdoelsayed2016** [comment]
it is saved correct you need the file same as photo or better using python to read it correct 

![image](https://github.com/DataScienceUIBK/ArabicaQA/assets/27821589/a2364ab3-ba87-4379-a379-e34232dc2b49)
